version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: DockerFileWordpress
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html/wp-content/plugins/elementor-consent-blocks-cookiebot
      - ./config-wordpress.sh:/usr/local/bin/config-wordpress.sh
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    command: /usr/local/bin/config-wordpress.sh


  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data:
